name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -p arti --locked --release
    - uses: actions/upload-artifact@v4
      with:
        name: arti-${{ runner.os }}-${{ runner.arch }}
        path: target/release/arti
